services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
    volumes:
      - /var/lib/jellyfin/:/config
      - /var/lib/jellyfin/cache:/cache
      - type: bind
        source: /ServerStore/Media/
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
    group_add:
      - 993
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.freno.me
    extra_hosts:
      - 'host.docker.internal:host-gateway'
