services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
    #user: 1000:1000 #need root access in /var/lib
    volumes:
      - /var/lib/jellyfin/:/config
      - /var/lib/jellyfin/cache:/cache
      - type: bind
        source: /ServerStore/
        target: /media
      #- type: bind
        #source: /path/to/media2
        #target: /media2
        #read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      #- type: bind
        #source: /path/to/fonts
        #target: /usr/local/share/fonts/custom
        #read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.freno.me
    extra_hosts:
      - 'host.docker.internal:host-gateway'
